apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: opentelemetry
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.145.0
  ports:
  - name: prom-exporter
    port: 8889
    protocol: TCP
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      batch:
        send_batch_size: 1000
        timeout: 10s
    exporters:
      # 核心修改点：这里必须写成 otlp_grpc，不能只写 otlp
      otlp_grpc/tempo: 
        endpoint: "tempo-distributor.logging.svc.cluster.local:4317"
        tls:
          insecure: true
      
      debug:
        verbosity: basic
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: otel_demo
        resource_to_telemetry_conversion:
          enabled: true
    connectors:
      spanmetrics: {}
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          # 核心修改点：这里也要对应改为 otlp_grpc/tempo
          exporters: [otlp_grpc/tempo, debug,spanmetrics]
        metrics:
          receivers: [spanmetrics]
          processors: []
          exporters: [prometheus]
