apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-debug
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot-debug
  template:
    metadata:
      labels:
        app: netshoot-debug
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/bash", "-c", "sleep infinity"]
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
