apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg16-ceph
  namespace: cnpg-system
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  primaryUpdateStrategy: unsupervised

  storage:
    size: 10Gi
    storageClass: ceph-rbd-sc

  walStorage:
    size: 5Gi
    storageClass: ceph-rbd-sc

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  monitoring:
    enablePodMonitor: false

  bootstrap:
    initdb:
      database: n8n
      owner: n8nuser
      secret:
        name: pg-secret

  superuserSecret:
    name: pg-superuser-secret
