# n8n-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-secret
  namespace: n8n
type: Opaque
stringData:
  DB_POSTGRESDB_USER: "n8nuser" # 替换为你的数据库用户名
  DB_POSTGRESDB_PASSWORD: "app123" # 替换为你的密码
  N8N_ENCRYPTION_KEY: "imustearnmoremoney" # 用于加密工作流凭据，务必保存
