apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: cnpg-system
type: kubernetes.io/basic-auth
stringData:
  username: n8nuser
  password: app123

---
apiVersion: v1
kind: Secret
metadata:
  name: pg-superuser-secret
  namespace: cnpg-system
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: postgres123
