apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-rbd-sc
provisioner: rbd.csi.ceph.com
parameters:
   clusterID: 594e535e-d82c-11f0-afa7-bc24112b746f
   pool: k8s-rbd
   imageFeatures: layering
   csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
   csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi-rbd
   csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
   csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi-rbd
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
   - discard
