apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: polinux/stress
        command: ["stress"]
        args: ["--cpu", "2", "--vm", "1", "--vm-bytes", "512M", "--timeout", "600s"]
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
